### ISSUE TITLE
リリースに向けたリデザイン

### ISSUE THREAD

**Issue by super-dog-human** [super-dog-human/teraconnect#9]

**Comment by SuperDogHuman** [comment]
0.2.0はこんな感じで

![スクリーンショット 2019-05-19 10 15 00](https://user-images.githubusercontent.com/15179279/57976618-90988400-7a1f-11e9-946c-4869d7828233.png)

**Comment by SuperDogHuman** [comment]
![Web 1280 – Top(heights)](https://user-images.githubusercontent.com/15179279/61394788-efcf2380-a8fe-11e9-918e-b3d2dc4d8e6e.png)

**Comment by super-dog-human** [comment]
![Web 1280 – Landing](https://user-images.githubusercontent.com/15179279/72221167-398d8380-359b-11ea-8946-cf57951a736e.png)
![iPhone SE](https://user-images.githubusercontent.com/15179279/63142629-7e7db000-c025-11e9-80f5-d04d4a69665c.png)
